---
title: "Project Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Project Title:  
Project:  
Team Members: Kayla Chea, Kevin Chou, Yanpei Xu, Sinan Zhao  

Info-201: Technical Foundations of Informatics  
The Information School  
University of Washington  
Autumn 2019  

### 1.0 Introduction
#### 1.1 Problem Situation.

#### 1.2 What is the problem? 

#### 1.3 What does it matter? 

#### 1.4 How it will be addressed? 

### 2.0 Research Questions
##### Research Question #1

##### Research Question #2

### 3.0 Possible Datasets
##### Data Set #1

##### Data Set #2

### 4.0 Information Visualization

### 5.0 Team Coordination
We will be meeting weekly on Friday from 2:00PM to 4:00PM. 

Individual Goals:

* Kayla Chea -
* Kevin Chou - 
* Yanpei Xu - 
* Sinan Zhao - 

We will communicate weekly through text. We will give each other feedback on working together by being honest and communicating our thoughts and feelings. We will addresss communication challenges or work breakdowns by directly addressing the issue. 

### 6.0 Questions for Teaching Team
N/A

### 7.0 References